[package]
name = "titan-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
titan-common = { path = "../titan-common" }
uuid.workspace = true
