[package]
name = "titan-skills"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
toml.workspace = true
titan-common = { path = "../titan-common" }
wait-timeout.workspace = true
wasmparser.workspace = true

[dev-dependencies]
tempfile.workspace = true
